import React, {useEffect,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import './style.css';
type Conversation={id:string;title:string;scenario:string;difficulty:string;correction:string};
type Message={id:string;conversation_id:string;seq:number;role:'user'|'assistant';content:string;corrections:string|null;cached_tokens:number|null};
type Config={baseUrl:string;model:string;hasKey:boolean;version:number};
type Thread={id:string;sentence:string;selection:string;messages:{role:string;content:string}[]};
async function api<T>(path:string,method='GET',body?:unknown):Promise<T>{const r=await fetch(`/api${path}`,{method,headers:{'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)});const data=await r.json();if(!r.ok)throw new Error(data.error||'请求失败');return data;}
const scenarios=[['','自由聊天'],['日常闲聊','日常闲聊'],['咖啡馆/餐厅点餐','咖啡馆/餐厅点餐'],['旅行','旅行'],['购物','购物'],['工作交流','工作交流']];
function App(){
  const [conversations,setConversations]=useState<Conversation[]>([]),[active,setActive]=useState<Conversation|null>(null),[messages,setMessages]=useState<Message[]>([]),[page,setPage]=useState<'chat'|'settings'>('chat');
  const [text,setText]=useState(''),[error,setError]=useState(''),[loading,setLoading]=useState(false),[custom,setCustom]=useState('');
  const [selection,setSelection]=useState<{message:Message;text:string;sentence:string;full:boolean}|null>(null),[explanation,setExplanation]=useState(''),[selectionBusy,setSelectionBusy]=useState(false),[question,setQuestion]=useState(''),[threads,setThreads]=useState<Record<string,Thread[]>>({});
  const [settings,setSettings]=useState<{main:Config;aux:Config}|null>(null),[test,setTest]=useState<Record<string,string>>({});
  const end=useRef<HTMLDivElement>(null);
  const refresh=async()=>setConversations(await api('/conversations'));
  const load=async(id:string)=>{const [c,m]=await Promise.all([api<Conversation>(`/conversations/${id}`),api<Message[]>(`/conversations/${id}/messages`)]);setActive(c);setMessages(m);setSelection(null);setError('');};
  useEffect(()=>{refresh().then(async()=>{const list=await api<Conversation[]>('/conversations');if(list[0])load(list[0].id);});},[]);
  useEffect(()=>end.current?.scrollIntoView({behavior:'smooth'}),[messages.length]);
  const create=async()=>{try{const c=await api<Conversation>('/conversations','POST',{title:'新对话',scenario:custom});await refresh();await load(c.id);setPage('chat');}catch(e){setError(String(e));}};
  const change=async(patch:Partial<Conversation>)=>{if(!active)return;try{const c=await api<Conversation>(`/conversations/${active.id}`,'PATCH',patch);setActive(c);await refresh();}catch(e){setError(String(e));}};
  const remove=async()=>{if(!active||!confirm('删除该对话及所有消息？'))return;await api(`/conversations/${active.id}`,'DELETE');setActive(null);setMessages([]);await refresh();};
  const send=async()=>{if(!active||!text.trim()||loading)return;const t=text;setText('');setLoading(true);setError('');try{await api(`/conversations/${active.id}/send`,'POST',{text:t});}catch(e){setError((e as Error).message);}finally{await loadMessages(active.id);setLoading(false);}};
  const retry=async()=>{if(!active||loading)return;setLoading(true);setError('');try{await api(`/conversations/${active.id}/retry`,'POST');}catch(e){setError((e as Error).message);}finally{await loadMessages(active.id);setLoading(false);}};
  const loadMessages=async(id:string)=>{setMessages(await api(`/conversations/${id}/messages`));await refresh();};
  const onSelect=(m:Message)=>{const s=window.getSelection();if(!s||s.isCollapsed)return;const target=s.anchorNode?.parentElement;const other=s.focusNode?.parentElement;const root=document.querySelector(`[data-message="${m.id}"]`);if(!target||!other||!root?.contains(target)||!root.contains(other))return;const selected=s.toString().trim();if(!selected)return;
    const content=m.content;const range=s.getRangeAt(0);const prefix=range.cloneRange();prefix.selectNodeContents(root);prefix.setEnd(range.startContainer,range.startOffset);const index=prefix.toString().length+range.toString().indexOf(selected);if(index<0||content.slice(index,index+selected.length)!==selected)return;
    const before=content.slice(0,index),after=content.slice(index+selected.length);
    const start=Math.max(before.lastIndexOf('. ')+2,before.lastIndexOf('! ')+2,before.lastIndexOf('? ')+2,before.lastIndexOf('\n')+1,0);
    const match=after.match(/[.!?](?:\s|$)|\n/);const endIndex=match?index+selected.length+match.index!+1:content.length;
    const sentence=content.slice(start,endIndex).trim();const full=selected.replace(/[.!?。！？\s]+$/,'')===sentence.replace(/[.!?。！？\s]+$/,'');
    setSelection({message:m,text:selected,sentence,full});setExplanation('');setQuestion('');setSelectionBusy(true);
    api<{explanation:string}>('/selection','POST',{messageId:m.id,selection:selected,sentence,fullSentence:full}).then(x=>setExplanation(x.explanation)).catch(e=>setExplanation((e as Error).message)).finally(()=>setSelectionBusy(false));
    api<Thread[]>(`/messages/${m.id}/threads`).then(t=>setThreads(p=>({...p,[m.id]:t}))).catch(()=>{});
  };
  const ask=async()=>{if(!selection||!question.trim())return;setSelectionBusy(true);try{const x=await api<{thread:Thread}>('/grammar','POST',{messageId:selection.message.id,selection:selection.text,sentence:selection.sentence,question});setThreads(p=>({...p,[selection.message.id]:[...(p[selection.message.id]||[]).filter(t=>t.id!==x.thread.id),x.thread]}));setQuestion('');}catch(e){setExplanation((e as Error).message);}finally{setSelectionBusy(false);}};
  const openSettings=async()=>{setSettings(await api('/settings'));setPage('settings');setError('');};
  return <div className="app"><aside><div className="brand">English Agent <small>英语对话练习</small></div><button className="primary" onClick={create}>＋ 新对话</button><label className="tiny">新对话情景（可自定义）</label><input value={custom} onChange={e=>setCustom(e.target.value)} list="scenarios" placeholder="自由聊天"/><datalist id="scenarios">{scenarios.map(([value,label])=><option key={label} value={value}>{label}</option>)}</datalist><div className="list">{conversations.map(c=><button key={c.id} className={active?.id===c.id?'selected':''} onClick={()=>{load(c.id);setPage('chat');}}><span>{c.title}</span><small>{c.scenario||'自由聊天'}</small></button>)}</div><button className="settingsButton" onClick={openSettings}>⚙ 模型设置</button></aside>
  {page==='settings'?<main className="settings"><header><h1>模型设置</h1><button onClick={()=>setPage('chat')}>返回对话</button></header><p className="muted">配置分别保存在本机。API Key 保存后只显示“已保存”；测试连接由你主动触发。</p>{settings&&(['main','aux'] as const).map(role=><ConfigForm key={role} role={role} config={settings[role]} onSaved={async()=>setSettings(await api('/settings'))} test={test[role]||''} setTest={s=>setTest(p=>({...p,[role]:s}))}/>)}{error&&<p className="error">{error}</p>}</main>:
  <main className="chat"><header>{active?<><div><input className="title" value={active.title} onChange={e=>setActive({...active,title:e.target.value})} onBlur={()=>change({title:active.title})}/><span className="muted">{active.scenario||'自由聊天'}</span></div><button className="danger" onClick={remove}>删除对话</button></>:<h1>开始练习英语</h1>}</header>
  {active&&<div className="controls"><label>情景 <select value={scenarios.some(([v])=>v===active.scenario)?active.scenario:'__custom'} onChange={e=>change({scenario:e.target.value==='__custom'?prompt('输入自定义情景')||active.scenario:e.target.value})}>{scenarios.map(([v,l])=><option key={l} value={v}>{l}</option>)}{!scenarios.some(([v])=>v===active.scenario)&&<option value="__custom">{active.scenario}</option>}<option value="__custom">自定义…</option></select></label><label>难度 <select value={active.difficulty} onChange={e=>change({difficulty:e.target.value})}><option value="easy">简单</option><option value="normal">常规</option><option value="challenge">挑战</option></select></label><label>主动纠错 <select value={active.correction} onChange={e=>change({correction:e.target.value})}><option value="off">关闭</option><option value="light">轻度</option><option value="standard">标准</option><option value="strict">严格</option></select></label></div>}
  <div className="messages">{!active?<div className="empty">点击“新对话”开始。先到模型设置填写主模型与辅助模型配置。</div>:messages.length===0?<div className="empty">用英语或中文开始对话。AI 的英语回复可以划词查看中文解释。</div>:messages.map(m=><div key={m.id} className={`message ${m.role}`}><div className="role">{m.role==='user'?'你':'English Agent'}</div><div className="bubble" data-message={m.id} onMouseUp={()=>m.role==='assistant'&&onSelect(m)}>{m.content}</div>{m.role==='assistant'&&m.corrections&&JSON.parse(m.corrections).length>0&&<div className="corrections"><strong>表达建议</strong>{JSON.parse(m.corrections).map((x:{original:string;improved:string;explanation:string},i:number)=><div key={i}><span>{x.original} → {x.improved}</span><small>{x.explanation}</small></div>)}</div>}{m.cached_tokens!==null&&<small className="muted">提供方报告的缓存输入：{m.cached_tokens} tokens</small>}</div>)}<div ref={end}/></div>
  {selection&&active&&<div className="selectionPanel"><div className="panelTop"><strong>{selection.full?'整句翻译':'中文释义'}：{selection.text}</strong><button onClick={()=>setSelection(null)}>✕</button></div><p>{selectionBusy&&!explanation?'解释中…':explanation}</p>{selection.full&&<><strong>追问语法</strong>{(threads[selection.message.id]||[]).filter(t=>t.sentence===selection.sentence).flatMap(t=>t.messages).map((x,i)=><p className="thread" key={i}><b>{x.role==='user'?'你':'辅助模型'}：</b>{x.content}</p>)}<div className="composer"><input value={question} onChange={e=>setQuestion(e.target.value)} onKeyDown={e=>e.key==='Enter'&&ask()} placeholder="针对这句话问一个语法问题"/><button disabled={selectionBusy||!question.trim()} onClick={ask}>追问语法</button></div></>}</div>}
  {error&&<p className="error">{error} {messages.at(-1)?.role==='user'&&<button disabled={loading} onClick={retry}>重试上一条</button>}</p>}{active&&<div className="composer mainComposer"><textarea value={text} onChange={e=>setText(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send();}}} placeholder="输入消息；Enter 发送，Shift+Enter 换行"/><button className="primary" disabled={loading||!text.trim()} onClick={send}>{loading?'回复中…':'发送'}</button></div>}</main>}
  </div>;
}
function ConfigForm({role,config,onSaved,test,setTest}:{role:'main'|'aux';config:Config;onSaved:()=>Promise<void>;test:string;setTest:(s:string)=>void}){
  const [baseUrl,setBaseUrl]=useState(config.baseUrl),[model,setModel]=useState(config.model),[apiKey,setApiKey]=useState(''),[clearKey,setClearKey]=useState(false),[saving,setSaving]=useState(false),[notice,setNotice]=useState('');
  const save=async()=>{setSaving(true);setNotice('');try{await api(`/settings/${role}`,'PUT',{baseUrl,model,...(apiKey?{apiKey}:{}),clearKey});setApiKey('');setClearKey(false);await onSaved();setNotice('已保存');}catch(e){setNotice((e as Error).message);}finally{setSaving(false);}};
  const testConnection=async()=>{setTest('测试中…');try{const r=await api<Record<string,string>>(`/settings/${role}/test`,'POST');setTest(Object.entries(r).map(([k,v])=>`${k}: ${v}`).join('；'));}catch(e){setTest((e as Error).message);}};
  return <section className="config"><h2>{role==='main'?'主模型 · 对话和纠错':'辅助模型 · 划词和语法'}</h2><label>Base URL<input value={baseUrl} onChange={e=>setBaseUrl(e.target.value)} placeholder="https://example.com/v1"/></label><label>Model ID<input value={model} onChange={e=>setModel(e.target.value)} placeholder="模型 ID"/></label><label>API Key <span className="muted">{config.hasKey?'已保存（不会显示明文）':'尚未保存'}</span><input type="password" autoComplete="new-password" value={apiKey} onChange={e=>setApiKey(e.target.value)} placeholder="留空则保留已有密钥"/></label><label className="check"><input type="checkbox" checked={clearKey} onChange={e=>setClearKey(e.target.checked)}/>清除已保存的密钥</label><div className="actions"><button className="primary" disabled={saving} onClick={save}>保存</button><button onClick={testConnection}>测试连接{role==='main'?'（含 compact）':''}</button><span className="muted">{notice} {test}</span></div></section>;
}
createRoot(document.getElementById('root')!).render(<App/>);
